services:
  app:
    build: .
    container_name: friends-menu
    ports:
      - "5223:3000"
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - ADMIN_SESSION_SECURE=false
    restart: unless-stopped
    volumes:
      - ./prisma:/app/prisma
      - ./public/uploads:/app/public/uploads
