import type { Metadata } from "next";
import { GlobalDebugPanelMount } from "@/components/GlobalDebugPanelMount";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LANG_COOKIE_KEY } from "@/i18n/config";
import { isLang } from "@/i18n/utils";
import { DEFAULT_LANG } from "@/i18n/config";
import { I18nProvider } from "@/i18n";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const cookieLang = cookieStore.get(LANG_COOKIE_KEY)?.value || "";
  const htmlLang = isLang(cookieLang) ? cookieLang : DEFAULT_LANG;
  return (
    <html
      lang={htmlLang}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <I18nProvider>{children}</I18nProvider>
        <GlobalDebugPanelMount />
      </body>
    </html>
  );
}
